import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from '@/lib/utils'
import HotHeader from "@/components/layout/header";
import HotMain from "@/components/layout/main";
import ThemeProvider from "@/components/context/theme";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`
        ${cn(
          "min-h-screen bg-background font-sans antialiased",
          inter.variable
          )} w-[100vw] h-[100vh]`
        } >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange>
          <HotHeader></HotHeader>
          <HotMain>
            {children}
          </HotMain>
        </ThemeProvider>
      </body>
  </html>
  );
}
